### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ecederstrand** [WebLogo/weblogo#103]
I'm currently doing a custom install containing https://github.com/WebLogo/weblogo/commit/9ca894f2b0e02a1bd436d173e5cd381d42725545

Would it be possible for you to release a new version containing the commit?

Also, it seems the latest releases are missing on pypi.org: https://pypi.org/project/weblogo/#history

**Comment by gecrooks** [comment]
New release 3.7.5 is live. 

`pip install weblogo --upgrade`

**Comment by ecederstrand** [comment]
Thanks!
