### ISSUE TITLE
Request Timeout Server Timeout

### ISSUE THREAD

**Issue by adeline-williams** [WebLogo/weblogo#104]
Hello, I am uploading a fasta file from my sequencing data but I am getting a timeout warning:

Request Timeout Server Timeout waiting for the HTTP request from the client.

Please advise?

**Comment by gecrooks** [comment]
The server seems to be working fine right now. Are you still having this error? And if so could you provide more details of what you are trying to do.

**Comment by adeline-williams** [comment]
Hi! Thanks for following up. I'm uploading a fasta file compiled with
23-30nt small RNA reads. I am wondering if the file is too big?
