### ISSUE TITLE
png files are corrupted

### ISSUE THREAD

**Issue by dunbrack** [WebLogo/weblogo#106]
I use the website for weblogo, http://weblogo.threeplusone.com/.

If I create a png with the website, it appears in the browser just fine. If I download, it can't be opened by Mac Preview program. It says "it may be damaged or use a format the Preview doesn't recognize." More than this, if I try to open it back up in the browse, Firefox can't read it. Neither can Safari.

this issue has been going on for YEARS. I forget sometimes, make this mistake, and then switch the output type to PDF. Then have to convert to png later, if I need it.

I just tried jpeg, and the same issue occurs. Initially, it appears in the browser. But after it is downloaded, it is corrupted and can't be opened by a graphics program.

These files can't be opened up in Gimp either.

Is this a known issue and can it be fixed?

Roland Dunbrack
Fox Chase Cancer Center
roland.dunbrack@gmail.com

**Comment by go-bears** [comment]
there's a small checkbox "Download to local drive " under the input box. 
For me, if that box is checked, Mac preview opens the logo & then I can save the image from preview.  I was able to re-open the test image from there as well. 
Often people want to preview the logo before downloading a final image.

**Comment by dunbrack** [comment]
go-bears : thanks! that works. that saves me a step of converting to png.
