### ISSUE TITLE
Why is the logo height higher than 4.3 for the conserved W in a logo?

### ISSUE THREAD

**Issue by deliacp** [WebLogo/weblogo#107]
Hi WebLogo developers,

I am not sure this is the right place for this question, but I am not sure of how to find the solution to my issue. Feel free to delete this comment if this is not the right place.

I am trying to create a logo for a set of 414 amino acid sequences with only five positions, where one of them is a very conserved tryptophan. According to the resulting logo, this tryptophan has a height larger than log2(20). Why is this? is WebLogo doing something behind the scenes that I have not considered?

I can attach the fasta file in case this helps.

Thanks a lot!

**Comment by gecrooks** [comment]
WebLogo v3 measures sequence conservation as the relative entropy to the background distribution. For proteins, the amino acid probability distribution is uneven, and W's are rare, so a fully conserved W position has more than log2(20) ~ 4.3 bits of information.

If instead you set the background composition to 'equiprobable' then a perfect conserved amino acid site will always report 4.3 bits of information.

**Comment by deliacp** [comment]
Thank you for the explanation. It indeed works changing the composition to equiprobable. I think this issue can be closed
