### ISSUE TITLE
WebLogo3.7.5 mismatch the type of sequence

### ISSUE THREAD

**Issue by Biosciman** [WebLogo/weblogo#110]
WebLogo3.7.5 mismatch the type of sequence
I've read the fasta documents containing the amino acid sequences. However, the WebLogo3.7.5 recognized it as a nucleotide sequences. Then the logo out was confusing.
`from weblogo import *`
`filename = 'AA0.fa'`
`seqs = read_seq_data(open(filename))`
`data = LogoData.from_seqs(seqs)`
`options = LogoOptions()`
`format = LogoFormat(data, options)`
`eps = txt_formatter(data, format)`
`with open('AA0.eps', 'wb') as f:`
`    f.write(eps)`

**Comment by gecrooks** [comment]
WebLogo tries to guess the sequence type. But because the amino acid and nucleotide alphabets overlap, sometimes it guesses wrong. To be safe, you can set the sequence type explicitly.
