### ISSUE TITLE
Feature Request: Support data format used by ATtRACT RBP database

### ISSUE THREAD

**Issue by feedmewifi** [WebLogo/weblogo#114]
[Example](https://attract.cnic.es/attract/static/matrix/326.txt) - UGCUG motif for Celf1

Each row contains the probability for U G C A  (respectively and in that order) delimited by tabs, should be fairly straightforward to parse :-)

**Comment by go-bears** [comment]
The posted example looks like mixed types of tabs and spaces for delimitation. Is that usually the case with this file format?

**Comment by feedmewifi** [comment]
It appears so. But also keep in mind the .split() string method in python, when used without any arguments, splits a string on every whitespace.

So maybe something like:

`
U,G,C,A = [],[],[],[]
link = "https://attract.cnic.es/attract/static/matrix/326.txt"
f = requests.get(link)
for line in f.text.split("\n"):
    base_probs = line.split()
    if base_probs == []:
        continue
    U.append(base_probs[0])
    G.append(base_probs[1])
    C.append(base_probs[2])
    A.append(base_probs[3])`

**Comment by go-bears** [comment]
The ATtRact database interface seems to be able to download files as comma-separated values and tab-separated values
https://attract.cnic.es/documentation

Maybe the data cleaning would be easier for you if you used csv formats and clean up the data for processing from there?
