### ISSUE TITLE
500 Internal Server Error when using WebLogo 3

### ISSUE THREAD

**Issue by YYeah** [WebLogo/weblogo#119]
I tried to use web-based WebLogo 3 (http://weblogo.threeplusone.com/create.cgi) to create logo. After clicking "Create WebLogo", it either showed a blank page or showed "500 Internal Server Error" as attached figure. I asked people at other places to try, they got the same error. and when I tried last time on Sep-12, it showed same issue.

![1633619879048](https://user-images.githubusercontent.com/31939486/136414170-d4ecc7b8-d296-4030-93a2-fcb4ad90ea9e.jpg)

**Comment by gecrooks** [comment]
Thanks for the heads up. The server does appear to be fubared for unknown reasons. Attempting to fix...
