### ISSUE TITLE
No reproducibility

### ISSUE THREAD

**Issue by shivamgupta0791** [WebLogo/weblogo#123]
for sequences more than 10 K weblogo doesn't show consistency. Sometime it generates logo and sometimes it shows random error like sequences are different length

**Comment by gecrooks** [comment]
Please provide a minimal example that exhibits this behavior.

**Comment by shivamgupta0791** [comment]
Hi Gavin,

Hope you are doing well.

Thank you so much for replying.

1. If I am choosing a resolution of more than 3600, I am getting
an inverted image of sequences. Please see the image (resolution-4000)
attached.

          weblogo -f P200_S37-CDR3-Padded.fasta -D fasta -o P200-S37-CDR3-2
-F jpeg -n 20 -s large --resolution 4000

2. which option do I need to choose to see the sequences at the bottom
(more mutation at one place) big and clear. Please see the attached
image.(1_Li)

3. How to give the desired seperation between two alphabets. I tried
all the options mentioned in tutorial but could not change the
separation distance. Please help me out with this issue.(2_Li)


With Regards
Shivam Gupta

**Comment by gecrooks** [comment]
A resolution of 4000 is enormous. I'd hazard a guess that Ghostscript is choking on the huge files you're generating. You should either generate a file in a vector format, such as PDF, or use a more reasonable resolution, e.g. 600.

**Comment by shivamgupta0791** [comment]
Dear Gavin,

Hope this email finds you well.

Is there any option to change the distance between two stacks of logos to
avoid overlapping among them?

[image: image.png]


Looking forward to your reply.
Have a nice day ahead.

With Regards
Shivam Gupta

**Comment by gecrooks** [comment]
I cannot see any image, so I don't know how it is that stacks are overlapping.

There is a variable `stack_margin` that controls the gap between stacks. But it's only accessible via the API, not the command line or GUI.
