### ISSUE TITLE
add a conda install option

### ISSUE THREAD

**Issue by sugatoray** [WebLogo/weblogo#124]
It will be nice to have a conda install option along side the ability to install with pip from PyPI.

I have already started the work of adding `weblogo` to conda-forge channel on conda. (PR: https://github.com/conda-forge/staged-recipes/pull/17283). Once the library is available on conda-forge, you can install it as follows:

```sh
conda install -c conda-forge weblogo
```

> Note: the conda package depends (builds from source) on the PyPI released version (`tar.gz` file) on weblogo.

**Comment by sugatoray** [comment]
cc: @ghuls @gecrooks

**Comment by ericmjl** [comment]
@sugatoray I believe weblogo is installable via bioconda rather than conda-forge. If so, you might be able to save yourself a bit of work :smile:. @ghuls and @gecrooks could you confirm, please?

**Comment by gecrooks** [comment]
There does seem to be a bioconda install, https://anaconda.org/bioconda/weblogo

Worth adding a note to the installation instructions.

**Comment by sugatoray** [comment]
@ericmjl  Thanks for mentioning `bioconda` channel as an option. However, I am not sure if a package from bioconda channel can be used while packaging up for `conda-forge` channel. So, far my understanding goes about conda-forge, you can only include packages from the channel itself as dependencies. There is a way out only in case your dependencies are optional. In that case you could use `run_constrained` for the optional dependencies, while creating the conda-forge package.

**Comment by go-bears** [comment]
@sugatoray 
#131  was resolved and closed. Do you still need any more information to complete the port to conda-forge?

**Comment by sugatoray** [comment]
Thank you. No, the porting was successful a few months ago. No other immediate requirements as of now.

**Comment by go-bears** [comment]
great to hear!

thanks for taking that on!
