### ISSUE TITLE
Multiple licenses mentioned for weblogo

### ISSUE THREAD

**Issue by sugatoray** [WebLogo/weblogo#131]
## License related problem for `weblogo` :fire: 

cc: @ghuls @gecrooks

However, there seems to be a problem with wblogo's license. The repository states it's available under MIT License. But the setup.py states it's available under BSD license. Which one is it?

This is also necessary for conda-forge packaging of weblogo: https://github.com/conda-forge/staged-recipes/pull/17283

Repo License file: [MIT License](https://github.com/WebLogo/weblogo/blob/master/LICENSE.txt)

> Parts of the code are covered by the MIT license, which is equivalent to the
BSD license apart from the third, no promotion clause. Please refer to
individual source code files for further details.

BSD License in setup.py:

https://github.com/WebLogo/weblogo/blob/98d21ab76bde322b2b809158f88bf6e594064be5/setup.py#L24-L27

https://github.com/WebLogo/weblogo/blob/98d21ab76bde322b2b809158f88bf6e594064be5/setup.py#L30-L34

**Comment by gecrooks** [comment]
It's the MIT license. I'll fix setup.py

**Comment by sugatoray** [comment]
Great. Could you please also push a new version to PyPI after this? Then I could go ahead and build the conda-pfrge package on top of that. Thank you.

**Comment by ericmjl** [comment]
@gecrooks and @sugatoray, thank you so much for making this happen! :smile:

**Comment by gecrooks** [comment]
Fixed with release 3.7.10
