### ISSUE TITLE
Incorrect character size?

### ISSUE THREAD

**Issue by jhfoxliu** [WebLogo/weblogo#133]
Hi,

I am drawing RNA base frequencies with weblogo==3.7.9 (and also other versions). I am confused that the character sizes/positions of some bases in low frequency are very strange in many output format like png, pdf, and svg. I tried weblogo on both CentOS and Ubuntu 18 and I got the same problem. The sequences in fasta file are in the same length and all in upper-case.

Here is my cmd (bits and probability work the same):

`weblogo -A rna -D fasta -F pdf --resolution 1000 --color-scheme classic  --composition none  -i -10 -P S_9 -f temp.fa`

![未标题-1](https://user-images.githubusercontent.com/20188476/148799496-b372ca39-55d5-43fc-851c-2fb5e18a3034.jpg)

**Comment by jhfoxliu** [comment]
I reopen this issue because I encounter the same issue in a new environment.

I am sure that the file is intact (sequences in the same length, no other characters out of AGCT). I run with CMD rather than call it with Python. Then I get the same problem when I am drawing the logo with `bits` as unit. I try it various version (3.5.0, 3.6.0, 3.7+), but I get the same issue.

![Bits](https://user-images.githubusercontent.com/20188476/181041254-904e6134-c51e-4590-91ed-55a6995166cb.png)
![Probability](https://user-images.githubusercontent.com/20188476/181041265-dcdfe949-fddd-4ca5-80c7-1e5a38eae224.png)

My environment is Ubuntu 20.04 LTS (WSL2). Exactly, I have the same issue in some cases on another computer with Ubuntu 18.

**Comment by jhfoxliu** [comment]
I read other closed issues. Guess this issue is from gs. So which version of gs should I swtich to?

**Comment by gecrooks** [comment]
9.23 works fine.

**Comment by jhfoxliu** [comment]
> 9.23 works fine.

Solved!
