### ISSUE TITLE
Large data set analysis

### ISSUE THREAD

**Issue by luozelook** [WebLogo/weblogo#136]
Can weblogo analyze a big data set? For example, around 500mb fasta file. I have tried many times but it always failed.

**Comment by go-bears** [comment]
@luozelook are you experiencing this issue with the website or the command line tool?

**Comment by luozelook** [comment]
Thanks for your response! The issue happened when I used website.
  
  
  
 Best,  

  
Yicheng
  
  
  
  

  
  
>

**Comment by go-bears** [comment]
You might want to try using the CLI tool for larger files. 

You can install the CLI version with `pip install weblogo`
More details on using the CLI tool can be found at : http://weblogo.threeplusone.com/manual.html

**Comment by luozelook** [comment]
Thanks!
