### ISSUE TITLE
problem with custom color scheme

### ISSUE THREAD

**Issue by romizambrano** [WebLogo/weblogo#145]
Hi, I am having a problem in using a **customized color scheme** for my sequence logo. I have done previous sequence logos with this tool before, and with custom color scheme, but for the last weeks i have been facing this problem.
I attach the custom color scheme and the error window.
![weblogo problem](https://user-images.githubusercontent.com/109995403/180883210-9c76a460-19ce-42b7-8426-827957cf35e6.png)
![custom color scheme](https://user-images.githubusercontent.com/109995403/180883215-f2828f63-7e25-48fb-bb2a-12ab9e7cc877.png)

**Comment by gecrooks** [comment]
Yup, it's foobared. We made (what should have been) a minor change to the color handling code recently, and my guess is that somehow that's has messed up. Will look into it...
