### ISSUE TITLE
Appearance of colored lines and tiny letters across the bottom of the web logo above the x-axis

### ISSUE THREAD

**Issue by rsalemi** [WebLogo/weblogo#147]
Hello,

Ive noticed with this version of web logo there is the appearance of a long colored line at the bottom of the weblogo above the x-axis. I am using a position weight matrix as the input. This happens when the output is png high res, pdf, or SVG. it does not happen for the low res png or the jpeg format. It happens regardless of size that either a line appears at the bottom of the logo, or small letters that are sometimes backwards appear at the bottom of the logo. 

I did not have this issue with Weblogo version 3.7.4 

This is my PWM input: 

P0	A	T	C	G
1	6	221	27	20
2	274	0	0	0
3	64	117	47	46
4	167	36	35	36
5	164	24	68	18
6	0	274	0	0

My settings are as followed:
Output format: .png, high res
Sequence type: Auto
Logo-size: Large
Stacks per line: 40
Ignore lower case: unchecked
Units: bits
Logo range: not filled out
Figure label: Not filled out
Scale stack width: Checked
Composition: E coli
Error bars: unchecked
Show sequence end labels: Unchecked
X-axis: Checked
Y-axis: checked
Y-axis scale: auto
y-axis tic spacing: 1
Color scheme: Classic (NA)

Thanks,
Rachel

**Comment by gecrooks** [comment]
I was able to reproduce the problem. I will look into it.

**Comment by YYeah** [comment]
Hi, this problem still exists. I was wondering if there is a way that I can use version 3.7.4, before it's fixed? Thank u

**Comment by ToHanwei** [comment]
In some of the lower versions, the problem also occurs with native tools, but the web version works fine

**Comment by ToHanwei** [comment]
Hi, this problem still exists. I was wondering if there is a way that I can use version 3.7.4, before it's fixed? Thank u

**Comment by ToHanwei** [comment]
I am using version 3.7.12 now, and I have encountered the same problem. Is there any solution? thank you

**Comment by gecrooks** [comment]
Resolved by upgrading ghostscript to version 10
