### ISSUE TITLE
Only "EPS" and "Data" available in Output Format options

### ISSUE THREAD

**Issue by Epannec** [WebLogo/weblogo#150]
Hi all,

I'm trying to run WebLogo 3 locally, but for some reason only "EPS" and "Data (plain text)" are available in the output options:

![image](https://user-images.githubusercontent.com/105773964/207846524-82827ea1-2f32-4106-9657-8689155232fd.png)

I suppose I'm missing some dependencies, but I can't seem to figure out which ones - I've installed all that is in the 'requirements'. Can somebody point me to the correct direction on how to tackle this?

Thank you in advance, 
Erwin

**Comment by gecrooks** [comment]
You need to install ghostscript and pdf2svg. (WebLogo uses them to convert generated postscript to other formats)

**Comment by gecrooks** [comment]
See issue #155. Somethings broken right now.
