### ISSUE TITLE
3.7.12 version_output format

### ISSUE THREAD

**Issue by LakminiSenavirathna** [WebLogo/weblogo#159]
Hi,

The new release only allows opening EPS and Data formats and not the the other formats such as JPG etc. But, this issue was not present in 3.7.11 as I was using the earliest version. Will you be able to enable the other output formats in the new release?

Thanks,
Lakmini

**Comment by Frank-Yeh-95** [comment]
Hey Lakmini,

I found a work around whereby you can save via EPS and then use https://www.filezigzag.com/online-converter to convert it to a desired file format. There's a 10 file limit per day, but they track it via cookies so if you clear your browser cookies for filezigzag.com/online-converter, you should be good to go! I hope they change it back soon though!

-Frank

**Comment by waskes** [comment]
the other options are in the dropdown menu but it is not working, seems that is a bug.

**Comment by gecrooks** [comment]
The underlying problem has been fixed (I hope) and format options have been reenabled.
