### ISSUE TITLE
Error while generating the png weblogo output of ~11 million aligned sequences

### ISSUE THREAD

**Issue by Shubhangi1397** [WebLogo/weblogo#161]
Hi,
I have large aligned sequence datasets (millions of sequences). I was able to generate weblogo output with ~1 million aligned sequence dataset but as I increased the dataset to ~7 million aligned sequences there was an error (see below). 

Is there a limit on the number of sequences that can be inputted for generating the weblogo output. 

![image](https://github.com/WebLogo/weblogo/assets/101345942/dff109d1-8993-4596-9700-8eb861aa48cc)

**Comment by gecrooks** [comment]
Hard to say why you're getting that error, but it doesn't appear to be because you have to many sequences.
