### ISSUE TITLE
Website certificate expired today, want to use for my university students

### ISSUE THREAD

**Issue by joannema7** [WebLogo/weblogo#162]
If this is not the place for this, send me along elsewhere if you know where I should go.
I teach a genomics course at the University of Illinois, and a fun project for them includes visiting the WebLogo site to create a logo with there sequence. 
I tried it today and coincidentally the certificate expired today. Who should be notified about updating their certificate?

**Comment by joannema7** [comment]
*their sequences. (ugh)

**Comment by go-bears** [comment]
Thank you @Lila14 and @joannema7 for the note. Great to know that website is being used in addition to the cli tool!

Low-bandwidth is the main culprit here, but hopefully this will get taken care of this quarter.

**Comment by gecrooks** [comment]
Fixed. Until next year.
