### ISSUE TITLE
Have residues that match a germline sequence not displayed

### ISSUE THREAD

**Issue by sonyahaupt** [WebLogo/weblogo#165]
Hello, Is there a function to generate a logo where residues that match a certain germline sequence for each position are not displayed? See attached, thank you

<img width="953" alt="image" src="https://github.com/WebLogo/weblogo/assets/154287598/40a0e64f-cd96-4437-b786-1015c4fec925">

**Comment by gecrooks** [comment]
Not with WebLogo, no.
