### ISSUE TITLE
Add support for meme data files.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WebLogo/weblogo#38]
```
http://meme.nbcr.net/meme/examples/sample-dna-motif.meme-io
```

Original issue reported on code.google.com by `GavinCro...@gmail.com` on 6 Mar 2014 at 12:54

**Comment by gecrooks** [comment]
Thanks for the suggestion. We'll add this feature when time permits.

**Comment by ghuls** [comment]
It might be an option to require biopython for it, which supports MEME and some other formats.
