### ISSUE TITLE
can I draw a sequence of letters with self-defined heights?

### ISSUE THREAD

**Issue by yil8** [WebLogo/weblogo#54]
Hi,

I'm wondering if I could use weblogo to draw a sequence of letters with self-defined heights. For example, I have a DNA sequence ACGT, and I have a vector of scores [1.0, 2.0, 3.0, 4.0] for each letter. Can I draw the sequence ACGT with each letter's height proportional to the given score through weblogo? It's different than the classical scenario that each position have a probability distribution over all the four letters.

Thanks so much!

**Comment by go-bears** [comment]
Not easily. You could use the API and build a logo programmatically. You could then set whatever heights you want

**Comment by rwsnyder** [comment]
You could also reverse mathematically calculate the ratios of sequences you’d need to arrive at the information content value you want to represent, and artificially create your library, then run it through the program. Hehehe.
-- 
Robert Wesley Snyder, PhD Candidate
NCSU/UNC Joint Biomedical Engineering Department
NCSU Department of Computer Science Bioinformatics Laboratory
