### ISSUE TITLE
weblogo: error: option -i: invalid integer value:

### ISSUE THREAD

**Issue by bengroves** [WebLogo/weblogo#69]
I've tried to use a transfac file to create a logo using weblogo in the command line, but I keep running into the error: "weblogo: error: option -i: invalid integer value: 'test_seqs.dat'". 

I started with the command like so:
weblogo -D transfac -F png -A rna  -i test_seqs.dat -o test_seqs.png

and subsequently shortened it to:
weblogo -i test_seqs.dat -o test_seqs.png

but no luck.

I've tried changing the values around from floats to integers and so on, to no avail. Any ideas?

**Comment by gecrooks** [comment]
Can you post a minimal example of your test_seqs.dat file? The most likely explanation is that weblogo doesn't like the formatting in that file for some reason.

**Comment by bengroves** [comment]
Sure, though it's possible that in simplifying it I've messed something else up too.

ID	Motif0
BF	S.Cerv
P0	A	C	G	U
00	1	1	1	1	C
01	1	1	1	1	C
XX
//

I've also tried something like this:
ID	Motif0
BF	S.Cerv
P0	A	C	G	T
00	0	1	0	0	C
01	0	0	0	1	T
XX
//

along with real data.

**Comment by gecrooks** [comment]
Try '-f' instead of '-i'
weblogo -D transfac -F png -A rna -f test_seqs.dat -o test_seqs.png

**Comment by bengroves** [comment]
oh. yeah. that wasn't terribly smart on my part. Thanks, it works!
