### ISSUE TITLE
Adding annotation curves onto the sequence logo

### ISSUE THREAD

**Issue by xiaoj12** [WebLogo/weblogo#70]
Hi,
I was wondering if anyone would have a suggestion on adding an annotation curve onto the sequence logo generated by Weblogo.  An example is attached below, but the curve I would like to add represent additional weights for each position.
![image](https://user-images.githubusercontent.com/6828820/30290920-22b1c352-96ff-11e7-823e-2020fb19c865.png)
JJ

**Comment by gecrooks** [comment]
Import figure into your favorite image editor and annotate away.
