### ISSUE TITLE
Customize the color for specific position(s)

### ISSUE THREAD

**Issue by biodavidjm** [WebLogo/weblogo#71]
Is it possible to change the color of one or many specific positions in the Logo? For example, is any of these possible?

- Apply the `color.scheme = 'chemistry'`, but modify one or many columns to 'yellow' (for all the characters in the column)
- Everything in one color for the entire sequence logo, but use a different color for some selected positions.

Thanks so much!

**Comment by he-leon** [comment]
Hi 
There's[ IndexColor(ColorRule):](https://github.com/WebLogo/weblogo/blob/master/weblogolib/colorscheme.py#L124) 
```python
#....
color_scheme = weblogolib.ColorScheme()
color_scheme.rules = [] # clears existing rules, might not be necessary in your case
color_scheme.rules.append(weblogolib.IndexColor(range(10), "#ffff00"))
logooptions = weblogolib.LogoOptions()
logooptions.color_scheme = color_scheme
#....
```
I didn't try it but something like this should draw the first 10 positions in yellow. You can also combine this with other [ColorRules](https://github.com/WebLogo/weblogo/blob/master/weblogolib/colorscheme.py).
Btw. I'm not a maintainer of weblogolib, so there might be a better way of doing this ;)

Greetings
Leonhard
