### ISSUE TITLE
class CustomColorScheme

### ISSUE THREAD

**Issue by phraber** [WebLogo/weblogo#79]
Hello, I am working to add a class to colorscheme.py that would use a different set of colors for each site (column).  The purpose is to indicate statistical associations with neutralizing antibody sensitivity, which vary with position.  For example, an 'N' in one position may be associated with sensitivity and in another position may be associated with resistance.  Is this of use to anyone or redundant with other efforts?  Any objections to using the re class to parse options from a cli-specified file?

A working example modified from weblogo-3.4 is online [here](https://www.hiv.lanl.gov/content/sequence/ANALYZEALIGN/analyze_align.html)

Thanks

**Comment by gecrooks** [comment]
Code to custom color columns was added in 3.5 by Kale Kundert. Please take a look to see whether or not that code covers your use-case. 

I don't object to using re to parse a configuration file as such. But it might be a better idea to use a standard file format, such as json or cvs, that python has a parser for already.
