### ISSUE TITLE
Installed name does not match pypi name

### ISSUE THREAD

**Issue by PikalaxALT** [WebLogo/weblogo#81]
Although the name of this package here and on pypi is `weblogo` (in that `pip install weblogo` installs this package), it must be imported as `weblogolib` or `corebio`.  This results in two distinct problems:

1) Because this behavior is documented nowhere, users attempting to use this package would be frustrated by the unintuitive import method.

2) Should another developer publish to pypi a package named `corebio` to be imported as `corebio`, it would incur a name conflict with your package.

**Comment by go-bears** [comment]
resolved with new release that supports python 3.7
