### ISSUE TITLE
build_test.sh typo

### ISSUE THREAD

**Issue by GildasLepennetier** [WebLogo/weblogo#82]
Hi
( First of all, I wanted to say I really like the simplicity and functionality of weblogo! )

in the build_test.sh, there is a typo ?

./weblogo --debug yes --fineprint "Test fin and fout" --fin cap.fa  --fout logo8.eps ||exit

This output the logo8.eps in . and not in ./tmp/logo8.eps

**Comment by gecrooks** [comment]
Yes, you're quite right. Fixed in branch dev3.7
