### ISSUE TITLE
python api

### ISSUE THREAD

**Issue by Zanathos113** [WebLogo/weblogo#83]
hi. i'm trying to use the python inline version of weblogo, but i can't find the api to use it, i try to find an example on the internet but i found nothing, can you help me with a little documentation or an example to use python weblogo?

thank you a lot.

**Comment by gecrooks** [comment]
The API is, alas, poorly documented at present. You're best bet is to read the code, and follow the path the command line client takes. You need to build a logooptions and logodata objects, and feed those to a logo formatter

**Comment by ewilson-Zymergen** [comment]
Hello! I've also been looking through some example weblogo api snippets to try to get a working example to run on my computer but I'm running into an issue trying to use the image formatter functions. Specifically, I keep getting a `TypeError: must be str, not bytes` when calling something like `weblogolib.png_formatter(data, format).` It seems to be coming from the `gs.convert()` function where I saw that there's a comment at the bottom that says ` # Python 2: out is a 'str', python 3 out is 'bytes'` so perhaps this is a known issue? But it was sounding like the api should be working with python 3 so perhaps I'm doing something incorrectly with it.

Here is an example workflow:

```
# example PWM to visualize
pwm = [[0.01344861, 0.10086455, 0.32084534, 0.5648415 ],[0.05475504, 0.14985591, 0.79538905, 0.        ],[0.50336215, 0.08741595, 0.35830932, 0.05091258],[0.4803074 , 0.16810759, 0.03746398, 0.31412104],[0.08933718, 0.07877041, 0.05763689, 0.77425552],[0.23150817, 0.17963497, 0.27185399, 0.31700288],[0.2401537 , 0.27569645, 0.20653218, 0.27761768],[0.27473583, 0.27089337, 0.21709894, 0.23727185]]
pwm = np.asarray(pwm)

# create data, options and format objects
data = weblogolib.LogoData.from_counts('ACGT', pwm)

options = weblogolib.LogoOptions(fineprint=False,
                                 logo_title="TEST", 
                                 color_scheme=weblogolib.classic, 
                                 stack_width=weblogolib.std_sizes["large"],
                                 logo_start=1, logo_end=8)

logo_format = weblogolib.LogoFormat(data, options)

# try producing png
weblogolib.png_formatter(data, logo_format)
```

This produces the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-134-f18ba5c9131d> in <module>()
----> 1 weblogolib.png_formatter(data, format)

~/anaconda3/envs/demo_erin/lib/python3.6/site-packages/weblogolib/__init__.py in png_formatter(data, format)
    766 def png_formatter(data, format):
    767     """ Generate a logo in PNG format."""
--> 768     return _bitmap_formatter(data, format, device="png")
    769 
    770 

~/anaconda3/envs/demo_erin/lib/python3.6/site-packages/weblogolib/__init__.py in _bitmap_formatter(data, format, device)
    720     gs = GhostscriptAPI()
    721     return gs.convert(device, eps,
--> 722                       format.logo_width, format.logo_height, format.resolution)
    723 
    724 

~/anaconda3/envs/demo_erin/lib/python3.6/site-packages/weblogolib/__init__.py in convert(self, format, postscript, width, height, resolution)
    228             error_msg += '\nReturn code: %i\n' % p.returncode
    229             if err is not None:
--> 230                 error_msg += err
    231             raise RuntimeError(error_msg)
    232 

TypeError: must be str, not bytes
```
Would you have any ideas for if there is another way I should be using the python API to avoid this error...? 

Thanks!

**Comment by gecrooks** [comment]
I ran your code under python 3.6.6 and it ran fine. Perhaps this is a Ghostscript error in disguise? 
> gs --version 
9.23

**Comment by ewilson-Zymergen** [comment]
Ah, thank you for the hint! That seems to have done the trick :) Thanks!
