### ISSUE TITLE
Publish API docs on readthedocs

### ISSUE THREAD

**Issue by gecrooks** [WebLogo/weblogo#92]

**Comment by go-bears** [comment]
resolved with new release

**Comment by ernstki** [comment]
I see from [newsgroup postings circa 2015](https://groups.google.com/forum/#!searchin/WebLogo/api/weblogo/LfMTzKJrVXE/kTxL0gWiIg0J) that API cleanup and documentation is a work-in-progress. Understand completely.

However, this (orphaned?) [`intro.rst`](https://github.com/WebLogo/weblogo/blob/master/docs/intro.rst) seems to be what the "[Application Programmer Interface (API)](http://weblogo.threeplusone.com/manual.html#API)" link in the User's Manual wants to point to, which is currently just a non-existent anchor.

The releases page for 3.7.0 says "Update API docs" and several documentation-related issues were closed around the time of this release. Was that just an oversight, or a regression?

**Comment by gecrooks** [comment]
Thanks, link fixed. The API docs can now be found at readthedocs. https://weblogo.readthedocs.io/en/latest/

**Comment by ernstki** [comment]
Super, thanks!
