### ISSUE TITLE
Look for gswin64c.exe in addition to gswin32c.exe

### ISSUE THREAD

**Issue by vineetbansal** [WebLogo/weblogo#97]
https://github.com/WebLogo/weblogo/blob/695e246e7d3800a1dfc3778d6f59b68c4b1d79c4/weblogo/logo_formatter.py#L248

On my 64-bit Windows, the .exe for ghostscript is named gswin64c.exe. So it's perhaps good for the `GhostscriptAPI` object to look for it in addition to `gswin32c.exe`.

I made this tweak on my local copy of logo_formatter.py and everything seems to be working fine.

**Comment by gecrooks** [comment]
Thanks, fixed.
